name: chatview
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 2.5.0
issue_tracker: https://github.com/SimformSolutionsPvtLtd/chatview/issues
repository: https://github.com/SimformSolutionsPvtLtd/chatview
publish_to: none

platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  any_link_preview: ^3.0.2
  audio_waveforms: ^1.2.0
  cached_network_image: ^3.4.1
  chatview_utils:
    git:
      url: https://github.com/SimformSolutionsPvtLtd/chatview_utils.git

  emoji_picker_flutter: ^4.3.0
  flutter:
    sdk: flutter
  image_picker: ">=0.8.9 <2.0.0"
  intl: ^0.20.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
